# View https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

# Dependency
orbs:
  node: circleci/node@1.1.6

# Declare Command
commands:
  install:
    description: |
      Install custom versions of NodeJS, and optionally NPM/Yarn, in any
      execution environment (Docker/Linux, macOS, machine) that does not have
      it preinstalled.

      Recommendation: It is highly recommended to utilize an environment such as Docker with Node preinstalled.
    parameters:
      install-npm:
        default: true
        description: Install NPM?
        type: boolean
      node-install-dir:
        default: /usr/local
        description: |
          Where should Node.js be installed?
        type: string
      node-version:
        default: ""
        description: |
          You may specify a full version tag ("13.11.0"), "latest", "current", "lts", or "stable". The latest (current) version of NodeJS will be installed by default. For a full list of releases, see the following: https://nodejs.org/en/download/releases
        type: string
      npm-version:
        default: latest
        description: |
          Pick a version of NPM to install: https://nodejs.org/en/download/releases
        type: string
    steps:
      - run:
          command: |
            # PLATFORM CHECK: mac vs. alpine vs. other linux

            SYS_ENV_PLATFORM=linux
            if uname -a | grep Darwin; then
              SYS_ENV_PLATFORM=darwin
            elif cat /etc/issue | grep Alpine; then
              SYS_ENV_PLATFORM=alpine
            fi
            echo "System is $SYS_ENV_PLATFORM"
            # FUNCTIONS

            get_node_index () {
              curl -Ls 'https://nodejs.org/dist/index.tab' | tail -n +2 | cut -f 1,3,10
            }
          name: Installing NodeJS <<parameters.node-version>>

jobs:
  install-node-example:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - node/install:
          install-npm: true
          node-version: latest
      - run: node --version
  install_env:
    executor:
      name: node/default
    steps:
      - install
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    version: 2
    install-and-build:
      jobs:
        - install_env:
            filters:
              branches:
                only:
                  - master
                  - develop
        - build-and-test:
            requires:
              - install_env
            filters:
              branches:
                only:
                  - master
                  - develop
